# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Geocodificacao
                                 A QGIS plugin
 Este plugin automatiza a geocodificação de endereços dispostos em CSV e cria um shapefile deste pontos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-11-18
        copyright            : (C) 2025 by Edson Tadeu da Silva Pinto
        email                : e.tadeu.eb@ime.eb.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Edson Tadeu da Silva Pinto'
__date__ = '2024-11-18'
__copyright__ = '(C) 2024 by Edson Tadeu da Silva Pinto'

def classFactory(iface):
    from .geocodificacao import GeocodificacaoPlugin
    return GeocodificacaoPlugin()
